### ISSUE TITLE
"No permission to fork process" during server startup

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-http#100]
On Fedora 26, with the following content in `test.pl`:

```prolog
:- use_module(library(http/http_unix_daemon)).
:- initialization http_daemon.
```

... I get an error that I have not seen earlier:

```
$ swipl test.pl --port=3001
ERROR: No permission to fork process `main' (running_threads([pce]))
```

The error goes away by adding `--interactive`.  I do not get this error on Ubuntu.

**Comment by JanWielemaker** [comment]
On 08/08/2017 10:30 PM, Wouter Beek wrote:
> On Fedora 26, with the following content in |test.pl|:
> 
> :-use_module(library(http/http_unix_daemon)).
> :-initialization  http_daemon.
> 
> ... I get an error that I have not seen earlier:
> 
> |$ swipl test.pl --port=3001 ERROR: No permission to fork process `main' 
> (running_threads([pce])) |
> 
> The error goes away by adding |--interactive|. I do not get this error 
> on Ubuntu.

I can't imagine this is OS dependent.  In modern versions you can
remove the `:-initialization  http_daemon.` as the library already
does `:-initialization(http_daemon,main).`.  That might help already.
The problem seems to be that xpce loaded and started by your code.
SWI-Prolog cannot fork after creating a thread.  As --interactive
prevents the fork in the first place, this helps.

If you run under systemd as a service you should also use the
`--no-fork` option, which fixes this problem as well.

	Cheers --- Jan

**Comment by wouterbeek** [comment]
Adding the `--no-fork` flag indeed solved this.  Closing...
