### ISSUE TITLE
HTTP Unix daemon does not respect --timeout option

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#114]
In the documentation of the HTTP Unix daemon, we find:

>  Other options are converted  by   argv_options/3  and  passed to
>   http_server/1.  For example, this allows for:
>     $ --workers=Count :

So I try to pass `--timeout=3`, but still the timeout is 60 seconds.

Steps to reproduce:

1. Download`proloxy.pl` from https://www.metalevel.at/proloxy/
2. Launch Proloxy with:

        $ swipl proloxy.pl --port=4090 --interactive  --timeout=3

4. Connect to Proloxy via Telnet, using:

        $ time telnet localhost 4090

The connection will be closed after 60 seconds, instead of 3 seconds.

Relatedly, there seems to be specialized code in the Unix daemon to pass the `workers` option to the HTTP server. Maybe `timeout` should be handled analogously, or both options should be instances of a more general mechanism to pass options through.

**Comment by JanWielemaker** [comment]
Turns out the options that are passed to the server are in the predicate server_option/1.  I've added the two timeout options there and added them to the usage message.

Ideally there should be one location where this is all declared instead of three.  This is not so easy though as some of the options for http_server/2 must be handled using all the complicated daemon script code while others can just be passed.  A little easier might be to generate `--help` from server_option/1.  Seems low priority.

**Comment by triska** [comment]
You also have removed the documentation for the `workers` option...

**Comment by JanWielemaker** [comment]
Oops.  Back

**Comment by triska** [comment]
Thank you!
