### ISSUE TITLE
parse_url/2 and uri_components/2 sometimes mistake host for protocol

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#12]
For example, `localhost` and `127.0.0.1` can be used interchangeably in many cases:

```
?- parse_url('localhost', Ps).
Ps = [protocol(http), host(localhost), path(/)].

?- parse_url('127.0.0.1', Ps).
Ps = [protocol(http), host('127.0.0.1'), path(/)].

?- uri_components('localhost', Cs).
Cs = uri_components(_G3573, _G3574, localhost, _G3576, _G3577).

?- uri_components('127.0.0.1', Cs).
Cs = uri_components(_G3573, _G3574, '127.0.0.1', _G3576, _G3577).
```

In each case, it is clear that `localhost` and `127.0.0.1` are the host, and the predicates behave exactly as expected.

However, when a _port_ is specified, we see for example the following difference:

<pre>
?- parse_url('127.0.0.1:4041', Ps).
Ps = [<b>protocol(http)</b>, host('127.0.0.1'), port(4041), path(/)].
</pre>

<pre>
?- parse_url('localhost:4041', Ps).
Ps = [<b>protocol(localhost)</b>, path('4041')].
</pre>

My expectation would be for `parse_url/2` to assume `http` as the default protocol in both cases, and again consider `127.0.0.1` and `localhost` as the host in _both_ cases.

Likewise, consider:

```
?- uri_components('127.0.0.1:4041', Cs).
Cs = uri_components('127.0.0.1', _G2659, '4041', _G2661, _G2662).

?- uri_components('localhost:4041', Cs).
Cs = uri_components(localhost, _G2659, '4041', _G2661, _G2662).
```

So, `uri_components/2` is consistently (and somewhat unexpectedly) regarding the host as the protocol or "Scheme" when a port is specified, yet differs from the way `parse_url/2` parses both URLs.

**Comment by wouterbeek** [comment]
Hi Markus, Thanks for filing this issue!  I do not agree that the examples you give at the beginning "behave exactly as expected".  For instance:

``` prolog
?- uri_components('localhost', Cs).
Cs = uri_components(_G3573, _G3574, localhost, _G3576, _G3577).
```

Notice that `localhost` is _not_ parsed as the authority but as the path component!  (Also notice that `uri_components/2` intends to extract the _authority_ not the _host_.  The latter is parsed with `uri_authority_components/2`.

**Comment by wouterbeek** [comment]
Hi Markus, Looking at your examples a little further I believe that `uri_components/2` is working correctly.  Let's take `localhost` as an example.  It is a relative IRI (grammar rule `relative-ref`) so it can include scheme nor authority (as it does not start with `//`).  `path-absolute` does not apply either (since that requires an initial `/`).  It can be parsed as `path-noscheme` since it is a non-empty sequence of alphabetic characters.

``` abnf
URI-reference = URI / relative-ref
relative-part = "//" authority path-abempty
                 / path-absolute
                 / path-noscheme
                 / path-empty
path-absolute = "/" [ segment-nz *( "/" segment ) ]
path-noscheme = segment-nz-nc *( "/" segment )
path-empty    = 0<pchar>
segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

**Comment by JanWielemaker** [comment]
In any case, the docs says the parsing is according to the regex as specified in  RFC-3986 (appendix B).   It doesn't really use a regular expression.  I consider only two reasons to change anything here: (1) the parser does not really follow the regex or (2) the regex is considered obsolete in a more recent RFC.

If you want to resolve a plain host name as `http://<hostname>` (as e.g. Firefox does), you must code that yourself.   The predicate is about breaking _well formed_ URIs.  It deliberately is not very strict in checking the wellformedness because many URIs in the wild do not conform to the strict grammar, but can be broken and processed correctly using the simple regex based approach.

**Comment by triska** [comment]
Thank you for looking into this. It indeed works as it ought to.
