### ISSUE TITLE
Content-encoding: gzip decompression does not work reliably

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#37]
Test case:

<pre>
$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.14-57-g6f9925a)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- <b>[library(http/http_client)]</b>.
true.

?- <b>[library(zlib)]</b>.
true.

?- <b>repeat,
     http_get('http://i.imgur.com/MOAsFWf.gifv', Data, [])
     sub_atom(Data, 0, 5, _, Start), 
     portray_clause(Start), false.</b>
</pre>

Sometimes the transparent gzip decompression works, and very often it doesn't:

<pre>
'\037\\213\\b\000\\000\'.
'&lt;!doc'.
'\037\\213\\b\000\\000\'.
'\037\\213\\b\000\\000\'.
'\037\\213\\b\000\\000\'.
'\037\\213\\b\000\\000\'.
'&lt;!doc'.
'&lt;!doc'.
'\037\\213\\b\000\\000\'.
'\037\\213\\b\000\\000\'.
'\037\\213\\b\000\\000\'.
etc.
</pre>

When I extend the test case to obtain the `Content-Encoding` header field, I get:

<pre>
?- <b>repeat,
     http_get('http://i.imgur.com/MOAsFWf.gifv', Data, [headers(Hs)]),
     ( memberchk(content_encoding(CE), Hs) -&gt; true ; CE = none),
     sub_atom(Data, 0, 5, _, Start),
     portray_clause(ce_start(CE, Start)), false.</b>
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(no, '&lt;!doc').
ce_start(no, '&lt;!doc').
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(gzip, '\037\\213\\b\000\\000\').
ce_start(no, '&lt;!doc').
ce_start(no, '&lt;!doc')
etc.
</pre>

**Comment by JanWielemaker** [comment]
If you use `?- debug(http(_)).`, you get sometimes this header field and sometimes not:

```
% Content-Encoding: gzip
```

Note the **Content**-Encoding.  According to the HTTP standard, this should have been
**Transfer**-encoding, turning it into a wire property that may be decoded by any party.  Content-Encoding is however a document property rather than a protocol property.   If you search for this, you see that Content-Encoding is used by many caching proxy servers (including www.swi-prolog.org)  because many clients do not understand Transfer-encoding.

If you fetch this document using the `curl`, you get exactly the same issue: sometimes you get a compressed document and sometimes not.

Since (I think) recently, (some?) CDN networks sometimes send compressed documents, despite the client does not have `gzip` in the Accept-Encoding header.

I'm unsure what to do with this.  How much do we break if we accept Content-Encoding as a synonym for Transfer-Encoding?   Would it be possible to persuade these server to use Transfer-encoding with some appropriate header?

**Comment by triska** [comment]
According to the following links, most web browsers and servers use `Content-Encoding` in the way that `Transfer-Encoding` was and is meant to be used by the HTTP specification:

[http://stackoverflow.com/questions/11641923/transfer-encoding-gzip-vs-content-encoding-gzip](http://stackoverflow.com/questions/11641923/transfer-encoding-gzip-vs-content-encoding-gzip)

[https://bugzilla.mozilla.org/show_bug.cgi?id=68517](https://bugzilla.mozilla.org/show_bug.cgi?id=68517)

`Content-Encoding: gzip` would be valid when downloading the content as an actual `.gz` file.

SWI should be strict in what it sends: Do not start to also send invalid headers. But it should be liberal in what it accepts: The sad fact of the matter seems to be that a large majority of servers do not follow the specification even in such a critical and important aspect as basic encoding properties.

**Comment by JanWielemaker** [comment]
That is more or less what I figured out as well.   Experimentally honour Content-encoding  as an alternative to Transfer-encoding (preferring the latter).  Seems to work well on the given URL and http://www.swi-prolog.org.  We'll see ...
