### ISSUE TITLE
Wishlist: Server-side SNI

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-http#55]
[**Server Name Indication**](https://en.wikipedia.org/wiki/Server_Name_Indication) (SNI) is an important and by now ubiquitously supported TLS extension that allows us to host different HTTPS sites from a **single&nbsp;IP** address.

Without server-side SNI (i.e., _status quo_ with the SWI HTTP and SSL libraries), essentially each domain for which we want to provide an HTTPS server needs to point to a separate IP, because the TLS handshake transfers the single **certificate** that can currently be specified, and that certificate is typically only valid for only a couple of (sub-)domains, if at all.

SNI extends this by providing the _right_ certificate _depending_ on the **domain** that the client used to access the site. This corresponds to the HTTP header field&nbsp;`Host`. However, critically, it takes place already at the TLS&nbsp;layer, _before_ the HTTP transfer is even initiated.

Supporting SNI therefore requires changes to _both_ the HTTP and SSL libraries (yeah!). I am filing this as an HTTP issue because I want to first discuss how such an option should be presented to **users**, and then extend the HTTP Unix daemon with options to make the information available in the first place.

Currently, the following are the most important options we _currently_ pass to the HTTP Unix daemon when launching an HTTPS server:
- `--certfile=C`
- `--keyfile=F`
- `--pwfile=P` _or_ `--password=P`

The reason `--pwfile` is provided is because the command line arguments can be easily inspected, whereas a password **file** can be made readable _only_ for users who need to access the private&nbsp;key. (As an aside, I sometimes find it quite frustrating that the HTTP Unix daemon may not have sufficient privileges at the time it reads the **certificate** and **key** files even when it is launched as root, because it drops the privileges before that point!)

To support server-side SNI, the above options need to be **generalized** so that they depend on the **hostname** that the client has used to connect to the server. That name is transferred by&mdash;you guessed it&mdash;_client_-side SNI, as _plain text_ because we need that information _before_ the TLS handshake takes place.

So, all of the above need to depend on hostnames, or rather patterns of hostnames, and maybe also a default certificate that is used if no matching host can be found. Option processing in the HTTP Unix daemon is already quite complex and error prone&nbsp;(#54). With server-side SNI, we need the ability to specify potentially many different certificates, keys and passwords that _depend_ on hostname patterns. We could cram these semantics into command line options too, but these options may become **arbitrarily&nbsp;long** and break system limits or become extremely hard to edit and understand. Therefore, I think the time has come to put this into a **config&nbsp;file**.

Here is a start to let us discuss how such an option could look like. First, all other command line options can _remain the same_. On the command line, I only need a single **new&nbsp;option**, let us call it:
- `--sni=File`

In such an SNI config file, we need to provide a series of **hostnames**, and for each such host:
- **certificate** that is used for that host
- **private key** that is used for that host
- if applicable, the **password** that protects the private key.

So, the SNI config file could for example consist of **Prolog facts** of the form:

```
sni(HostRegexp, [certfile=C,keyfile=K,pwfile=P]).
```

Instead of `pwfile`, `password` can _also_ be supported, in analogy to the command line options that are currently used.

So, we may for example have entries like:

```
sni('swish.swi-prolog.org', [certfile='swish.crt',keyfile='swish.key']).
sni('.*swi-prolog.org', [certfile='swi.crt',keyfile='swi.key',pwfile='swi.pwd']).
```

The hostname matching could be _regexp-based_, or, in a first step, _exact_. Conceptually, when a client initiates a TLS handshake, then the server fetches the used host name and uses the **first&nbsp;matching** certificate and private key for the remainder of the connection. If regexps are used, then this naturally subsumes the "default" case, because we can use the empty regexp to match all remaining hosts.

If these options could somehow be made available as part of the context that is passed around in the HTTP server libraries, then I can modify the SSL library to fetch the matching certificate based on these options. Please let me know what you think. Thank you!

**Comment by JanWielemaker** [comment]
> As an aside, I sometimes find it quite frustrating that the HTTP Unix daemon may not have sufficient privileges at the time it reads the file even when it is launched as root, because it drops the privileges before that point!

???  store_passwd/1, which reads the passwd from the file and stores it in a global variable is called before switching user.

**Comment by JanWielemaker** [comment]
I'm not so sure we want this as part of http_unix_daemon.pl anyway.   It seems to make the library overly complicated, getting further away from the primary aim: deal with integration into the Unix daemon infrastructure.   This was, as I wrote it, primarily based on fork, detach from controlling terminal, dealing with privileged operations, logging, etc.   Modern daemon frameworks do not need most of this, but that is a different issue.

The rest of server configuration, such as defining HTTP locations, authentication, time limits, etc are all done in the server infrastructure in Prolog (I have a discussion with Matt for generalizing authentication as we have too many alternatives that partly overlap).

I think the SNI infrastructure should simply call a hook that obtains the certificate details for a given host.  
That hook is probably called from the core SSL and/or HTTP libraries.  The default just behaves as if SNI doesn't exist.   If you want SNI, you define rules for this, for example:

```
http:sni_host('swish.swi-prolog.org', [certfile='swish.crt',keyfile='swish.key']).
```

If a project wants a fancy configuration file it can define whatever it likes.  I can imagine you put the files in a directory with names derived from the hostname.   As a side note, it might be better if the hook exchanges the certificates, keys and password rather than files that contain them so you can put this data in a database, read it into Prolog before switching the user, etc.

The primary application for SNI that I see is your proxy server.  I'm sure you can integrate this hook into the overall proxy configuration.   Doing virtual hosting is not very common for an application framework.  Applications I can imagine would serve uniform operations over a large number of domains were you probably want dedicated rules to manage the certificates.

**Comment by triska** [comment]
First, a clarification: The server drops privileges before it reads the **certificate** and **private key** files, and that is a problem for example when you want to read _Let's&nbsp;Encrypt_ certificates directly: They are stored in `/etc/letsencrypt/live/<domain>/...`, where only **root** has access, at least by default. It's only an annoyance, and somewhat inconsistent with the password file, which _is_ read before privileges are dropped. I have clarified this in the original post.

Second, yes, server-side SNI is mostly interesting for the SWI-based proxy server [**Proloxy**](https://github.com/triska/proloxy). In fact, _everything_ HTTPS-related is only interesting for that server, at least to me: I use plain HTTP between the proxy and further servers on the some machine, so the proxy serves as the single HTTPS endpoint.

The hook you mention would greatly benefit this use case, and I am certain that I can integrate this nicely in Proloxy. This would be nice for all users who run multiple domains on a single&nbsp;IP, using a Prolog-based toolchain throughout.

**Comment by JanWielemaker** [comment]
> First, a clarification: The server drops privileges before it reads the certificate and private key files, and that is a problem for example when you want to read Let's Encrypt certificates directly: They are stored in /etc/letsencrypt/live/<domain>/..., where only root has access, at least by default. It's only an annoyance, and somewhat inconsistent with the key file, which is read before privileges are dropped. I have clarified this in the original post.

I see.  The private key file is not protected by a password?   From Matt I understood there is nothing sensitive to the certificate itself.   The private key file is the sensitive part and is normally protected by a passphrase.  That is the only thing then that needs protection.

Seems we need certificates and keys as Prolog strings rather than files.  I don't know the status of that.

**Comment by triska** [comment]
All of this is now implemented.
